name: ali-oss-uploader
author: Leftsky <leftsky@vip.qq.com>
description: 阿里云OSS上传Action
branding:
  icon: 'upload-cloud'
  color: 'orange'
inputs:
  region:
    description: '阿里云OSS地域'
    required: true
    default: ''
  endpoint:
    description: '阿里云OSS Endpoint'
    required: true
    default: ''
  key-id:
    description: '阿里云OSS AccessKeyId'
    required: true
    default: ''
  key-secret:
    description: '阿里云OSS AccessKeySecret'
    required: true
    default: ''
  bucket:
    description: '阿里云OSS Bucket'
    required: true
    default: ''
  dir:
    description: '需要上传的文件或文件夹'
    required: true
    default: ''
  target-dir:
    description: '上传到OSS的目标文件夹'
    required: true
    default: ''
runs:
  using: "node20"
  main: "dist/index.js"