name: ali-oss-uploader
author: Leftsky <leftsky@vip.qq.com>
description: 阿里云OSS上传Action
branding:
  icon: 'upload-cloud'
  color: 'orange'
inputs:
  region:
    description: '阿里云OSS地域'
    required: false
  endpoint:
    description: '阿里云OSS Endpoint'
    required: false
  key-id:
    description: '阿里云OSS AccessKeyId'
    required: true
  key-secret:
    description: '阿里云OSS AccessKeySecret'
    required: true
  bucket:
    description: '阿里云OSS Bucket'
    required: true
  dir:
    description: '需要上传的文件或文件夹'
    required: true
  target-dir:
    description: '上传到OSS的目标文件夹'
    required: true
outputs:
  url:
    description: '上传成功后的URL'
runs:
  using: "node20"
  steps:
    - run: 'index.js'
